CREATE TABLE users (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP,
    user_type VARCHAR(31) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(10),
    medical_history TEXT,
    blood_type VARCHAR(5),
    allergies TEXT,
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    specialization VARCHAR(100),
    license_number VARCHAR(50) UNIQUE,
    years_of_experience INTEGER,
    qualifications TEXT,
    consultation_fee DECIMAL(10, 2),
    bio TEXT,
    available BOOLEAN,
    employee_number VARCHAR(50) UNIQUE,
    pharmacy_location VARCHAR(100)
);

CREATE TABLE appointments (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP,
    patient_id UUID NOT NULL,
    doctor_id UUID NOT NULL,
    appointment_date TIMESTAMP NOT NULL,
    duration INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason_for_visit VARCHAR(500),
    notes TEXT,
    reminder_sent BOOLEAN NOT NULL,
    reminder_sent_at TIMESTAMP,
    cancelled_by VARCHAR(50),
    cancellation_reason TEXT,
    cancellation_date TIMESTAMP,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES users (id),
    CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id) REFERENCES users (id)
);

CREATE TABLE medical_records (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP,
    patient_id UUID NOT NULL,
    doctor_id UUID NOT NULL,
    appointment_id UUID,
    diagnosis TEXT,
    treatment TEXT,
    prescription TEXT,
    test_results TEXT,
    vital_signs TEXT,
    follow_up_required BOOLEAN NOT NULL,
    follow_up_date DATE,
    notes TEXT,
    record_date DATE NOT NULL,
    medical_record_type VARCHAR(50),
    is_confidential BOOLEAN NOT NULL,
    CONSTRAINT fk_medical_record_patient FOREIGN KEY (patient_id) REFERENCES users (id),
    CONSTRAINT fk_medical_record_doctor FOREIGN KEY (doctor_id) REFERENCES users (id),
    CONSTRAINT fk_medical_record_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id)
);

CREATE TABLE token_blacklist (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP,
    token VARCHAR(2048) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    blacklisted_at TIMESTAMP NOT NULL
);

CREATE TABLE prescription_orders (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP,
    doctor_id UUID NOT NULL,
    doctor_name VARCHAR(100) NOT NULL,
    patient_name VARCHAR(100) NOT NULL,
    drug_name VARCHAR(200) NOT NULL,
    dosage VARCHAR(100) NOT NULL,
    instructions TEXT,
    status VARCHAR(20) NOT NULL,
    ordered_at TIMESTAMP NOT NULL,
    dispensed_at TIMESTAMP
);